### ISSUE TITLE
Add sighting not working

### ISSUE THREAD

**Issue by Bribabri** [mksanderson/pokeswarm#16]
Er..sorry but I think I preferred the old version of adding pokemon. It feels like everything is a bit squashed up on this screen. When you start typing the name of the pokemon, the map is very small and cut off and it's not immediately obvious what you're supposed to do. Sometimes the map only scrolls inside itself and not the page. The save and current location buttons are over the text and kind of blend in to the rest of the page. It was working yesterday but not save doesn't work. Also it was annoying (when it did work) that the add screen didn't disappear when you'd pressed save - giving you feedback that your pokemon had been added. Although I do like how the add screen has more space. Perhaps a solution would be for it to be a 2 step process - so after you add the name - there is a next button that takes you to where you add it on the map so the map isn't cut off or something.

**Comment by mksanderson** [comment]
Fixed issue with form not submitting.

Current feedback method is that the pokemon appears on the map when you add it, but would like to add a notification. Thinking an app style notification that comes down at the top and then can be dismissed? Thoughts?

In terms of design, I'd like to keep it to 1 page just because that way you can quickly keep adding more without too much perceived stuffing around. Maybe the structure of the form needs a rethink.

Current idea is across each of the views you have:
- bottom action bar
- secondary actions above this
- main view

But this is just a quick way of getting all the bits and pieces in there. Probably needs a more cohesive design...I based the idea of this off of the sketches you sent me (with the bottom bar etc).

In regards to the form, there will be more fields in future as well:
- Option to add a type of thing - ie: add a pokestop, add a pokemon
- Customise date/time - default to your current time but you can change it

**Comment by Bribabri** [comment]
Don't know - would have to see it. The bar at the bottom is neater though.
